name: Run Notify Script

on:
    push:
        branches:
            - main
    workflow_dispatch: # Allows the workflow to be manually triggered


jobs:
    run-script:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.x'

            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
              env:
                DISTRICT: ${{vars.DISTRICT}}
                LOCALITY: ${{vars.LOCALITY}}
                BOT_TOKEN: ${{secrets.BOT_TOKEN}}
                CHAT_ID: ${{secrets.CHAT_ID}}

            - name: Run notify.py
              run: python notify.py